return {
	name = "Kyusyu_C",
	displayName = "九州",
	islands = {
		"Kyusyu_01",
		"Kyusyu_02",
		"Kyusyu_03",
		"Kyusyu_04",
		"Kyusyu_05",
		"Kyusyu_06",
		"Kyusyu_07",
		"Kyusyu_08",
		"Kyusyu_09",
		"Kyusyu_10",
		"Kyusyu_11",
		"Kyusyu_12",
		"Kyusyu_13",
		"Kyusyu_14",
		"Kyusyu_15",
		"Kyusyu_16",
		"Kyusyu_17",
		"Kyusyu_18",
		"Kyusyu_19",
		"Kyusyu_20",
		"Kyusyu_21",
		"Kyusyu_22",
		"Kyusyu_23",
		"Kyusyu_24",
		"Kyusyu_25",
		"Kyusyu_26",
		"Kyusyu_27",
		"Kyusyu_28",
		"Kyusyu_29",
		"Kyusyu_30",
		"Kyusyu_31",
		"Kyusyu_32",
		"Kyusyu_33",
		"Kyusyu_34",
		"Kyusyu_35",
		"Kyusyu_36",
		"Kyusyu_37",
		"Kyusyu_38",
		"Kyusyu_39",
		"Kyusyu_40",
		"Kyusyu_41",
		"Kyusyu_42",
		"Kyusyu_43",
		"Kyusyu_44",
		"Kyusyu_45",
		"Kyusyu_46",
		"Kyusyu_47",
		"Kyusyu_48",
		"Kyusyu_49",
		"Kyusyu_50",
		"Kyusyu_51",
		"Kyusyu_52",
		"Kyusyu_53",
		"Kyusyu_54",
		"Kyusyu_55",
		"Kyusyu_56",
		"Kyusyu_57",
		"Kyusyu_58",
		"Kyusyu_59",
		"Kyusyu_60",
		"Kyusyu_61",
		"Kyusyu_62",
		"Kyusyu_63",
		"Kyusyu_64",
		"Kyusyu_65",
		"Kyusyu_66",
		"Kyusyu_67",
		"Kyusyu_68",
		"Kyusyu_69",
		"Kyusyu_70",
		"Kyusyu_71",
		"Kyusyu_72",
		"Kyusyu_73",
		"Kyusyu_74",
		"Kyusyu_75",
		"Kyusyu_76",
		"Kyusyu_77",
		"Kyusyu_78",
		"Kyusyu_79",
		"Kyusyu_80",
		"Kyusyu_81",
		"Kyusyu_82",
		"Kyusyu_83",
		"Kyusyu_84",
		"Kyusyu_85",
		"Kyusyu_86",
		"Kyusyu_87",
		"Kyusyu_88",
		"Kyusyu_89",
		"Kyusyu_90",
		"Kyusyu_91",
		"Kyusyu_92",
		"Kyusyu_93",
		"Kyusyu_94",
		"Kyusyu_95",
		"Kyusyu_96",
		"Kyusyu_97",
		"Kyusyu_98",
		"Kyusyu_99",
		"Kyusyu_100",
		"Kyusyu_101",
		"Kyusyu_102",
		"Kyusyu_103",
	},
	--544.5, 31.2, 323.3
	portals = {
		-- {
		-- 	name = "Portal_01",
		-- 	islandName = "Hokkaido_01",
		-- 	toZone = "Hokkaido_C",
		-- 	position = { 447.4, 31.2, 680.8 }, -- ★絶対座標
		-- 	-- model = "crystal1",
		-- 	model = "Door"
		-- 	size = 4.5,
		-- 	label = "→ 北海道へ",
		-- 	snapToGround = true,
		-- 	heightOffset = 1,
		-- 	rotate = true,
		-- },
		{
			isFastTravelTarget = true,
			name = "九州の桜島",
			-- islandName = "Hokkaido_01",
			toZone = "Hokkaido_C",
			position = { 447.2, 31.3, 685.2 }, --866.7, 24.2, 491.5
			spawnPosition = { 870.6, 31.2, 492.7 },
			model = "Door",
			size = 1,
			label = "→ 北海道へ",
			snapToGround = true,
			heightOffset = 0,
			rotate = true,
			rotation = { 0, 45, 0 },
		},
	},
	paths = {},
	fieldObjects = {
		{
			model = "box_closed",
			position = { 90.3, 31.2, 795.9 },
			mode = "fixed",
			size = 1,
			rotation = { 0, 0, 0 },
			stickToGround = false, -- 省略可（trueが既定）
			groundOffset = 0, -- 芝生で少し浮かせたい時
			alignToSlope = false, -- 斜面に木を傾けたくないならfalse

			interaction = {
				type = "chest", -- インタラクションタイプ
				action = "開ける", -- ボタンに表示されるテキスト
				key = "E", -- キーバインド
				range = 8, -- インタラクション可能距離（スタッド）

				-- 宝箱固有の情報
				chestId = "hokkaido_chest_03", -- ユニークID
				openedModel = "box_opened", -- 開いた状態のモデル名
				rewards = {
					{ item = "ゴールド", count = 120 },
				},
				displayDuration = 3, -- 報酬表示時間（秒）
			},
		},
		{
			model = "Tree1",
			position = { 94.3, 31.2, 799.9 },
			size = 1.5,
			rotation = { 0, 0, 0 },
			stickToGround = true, -- 省略可（trueが既定）
			groundOffset = 0.15, -- 芝生で少し浮かせたい時
			alignToSlope = true, -- 斜面に木を傾けたくないならfalse
		},
	},
	BGM = "",
	BGMVolume = 0.2,
}
