return {
	{
		name = "Kyusyu_01",
		centerX = 578,
		centerZ = 326,
		sizeXZ = 250,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = true,
		oceanRadius = 6000,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_02",
		centerX = 549,
		centerZ = 484,
		sizeXZ = 250,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_03",
		centerX = 468,
		centerZ = 540,
		sizeXZ = 161,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_04",
		centerX = 568,
		centerZ = 574,
		sizeXZ = 149,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_05",
		centerX = 564,
		centerZ = 642,
		sizeXZ = 149,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_06",
		centerX = 466,
		centerZ = 228,
		sizeXZ = 129,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_07",
		centerX = 530,
		centerZ = 156,
		sizeXZ = 121,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_08",
		centerX = 588,
		centerZ = 188,
		sizeXZ = 121,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_09",
		centerX = 482,
		centerZ = 98,
		sizeXZ = 100,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_10",
		centerX = 451,
		centerZ = 165,
		sizeXZ = 100,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_11",
		centerX = 396,
		centerZ = 571,
		sizeXZ = 100,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_12",
		centerX = 467,
		centerZ = 291,
		sizeXZ = 98,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_13",
		centerX = 396,
		centerZ = 188,
		sizeXZ = 96,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_14",
		centerX = 338,
		centerZ = 210,
		sizeXZ = 90,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_15",
		centerX = 638,
		centerZ = 188,
		sizeXZ = 88,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_16",
		centerX = 724,
		centerZ = 307,
		sizeXZ = 82,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_17",
		centerX = 687,
		centerZ = 161,
		sizeXZ = 78,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_18",
		centerX = 655,
		centerZ = 258,
		sizeXZ = 78,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_19",
		centerX = 700,
		centerZ = 271,
		sizeXZ = 78,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_20",
		centerX = 703,
		centerZ = 366,
		sizeXZ = 78,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_21",
		centerX = 676,
		centerZ = 398,
		sizeXZ = 78,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_22",
		centerX = 664,
		centerZ = 444,
		sizeXZ = 78,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_23",
		centerX = 509,
		centerZ = 635,
		sizeXZ = 78,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_24",
		centerX = 504,
		centerZ = 77,
		sizeXZ = 78,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_25",
		centerX = 504,
		centerZ = 690,
		sizeXZ = 71,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_26",
		centerX = 488,
		centerZ = 702,
		sizeXZ = 71,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_27",
		centerX = 498,
		centerZ = 744,
		sizeXZ = 65,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_28",
		centerX = 753,
		centerZ = 338,
		sizeXZ = 58,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_29",
		centerX = 588,
		centerZ = 712,
		sizeXZ = 58,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_30",
		centerX = 383,
		centerZ = 716,
		sizeXZ = 58,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_31",
		centerX = 390,
		centerZ = 635,
		sizeXZ = 58,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_32",
		centerX = 370,
		centerZ = 610,
		sizeXZ = 58,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_33",
		centerX = 464,
		centerZ = 612,
		sizeXZ = 57,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_34",
		centerX = 422,
		centerZ = 626,
		sizeXZ = 57,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_35",
		centerX = 404,
		centerZ = 652,
		sizeXZ = 57,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_36",
		centerX = 390,
		centerZ = 682,
		sizeXZ = 57,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_37",
		centerX = 331,
		centerZ = 447,
		sizeXZ = 56,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_38",
		centerX = 482,
		centerZ = 782,
		sizeXZ = 52,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_39",
		centerX = 308,
		centerZ = 238,
		sizeXZ = 51,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_40",
		centerX = 282,
		centerZ = 216,
		sizeXZ = 51,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_41",
		centerX = 548,
		centerZ = 92,
		sizeXZ = 45,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_42",
		centerX = 382,
		centerZ = 130,
		sizeXZ = 45,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_43",
		centerX = 360,
		centerZ = 160,
		sizeXZ = 45,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_44",
		centerX = 404,
		centerZ = 750,
		sizeXZ = 43,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_45",
		centerX = 254,
		centerZ = 202,
		sizeXZ = 43,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_46",
		centerX = 416,
		centerZ = 766,
		sizeXZ = 41,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_47",
		centerX = 376,
		centerZ = 744,
		sizeXZ = 41,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_48",
		centerX = 350,
		centerZ = 738,
		sizeXZ = 41,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_49",
		centerX = 394,
		centerZ = 434,
		sizeXZ = 40,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_50",
		centerX = 343,
		centerZ = 420,
		sizeXZ = 40,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_51",
		centerX = 357,
		centerZ = 354,
		sizeXZ = 38,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_52",
		centerX = 378,
		centerZ = 338,
		sizeXZ = 38,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_53",
		centerX = 377,
		centerZ = 320,
		sizeXZ = 38,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_54",
		centerX = 314,
		centerZ = 170,
		sizeXZ = 38,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_55",
		centerX = 448,
		centerZ = 680,
		sizeXZ = 38,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_56",
		centerX = 460,
		centerZ = 800,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_57",
		centerX = 504,
		centerZ = 774,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_58",
		centerX = 524,
		centerZ = 757,
		sizeXZ = 37,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_59",
		centerX = 356,
		centerZ = 282,
		sizeXZ = 36,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_60",
		centerX = 343,
		centerZ = 257,
		sizeXZ = 36,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_61",
		centerX = 328,
		centerZ = 257,
		sizeXZ = 36,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_62",
		centerX = 324,
		centerZ = 470,
		sizeXZ = 35,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_63",
		centerX = 308,
		centerZ = 144,
		sizeXZ = 35,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_64",
		centerX = 363,
		centerZ = 536,
		sizeXZ = 32,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_65",
		centerX = 455,
		centerZ = 373,
		sizeXZ = 32,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_66",
		centerX = 436,
		centerZ = 385,
		sizeXZ = 32,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_67",
		centerX = 278,
		centerZ = 288,
		sizeXZ = 32,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_68",
		centerX = 266,
		centerZ = 271,
		sizeXZ = 32,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_69",
		centerX = 333,
		centerZ = 288,
		sizeXZ = 32,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_70",
		centerX = 549,
		centerZ = 60,
		sizeXZ = 32,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_71",
		centerX = 410,
		centerZ = 136,
		sizeXZ = 32,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_72",
		centerX = 442,
		centerZ = 818,
		sizeXZ = 29,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_73",
		centerX = 368,
		centerZ = 436,
		sizeXZ = 29,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_74",
		centerX = 338,
		centerZ = 514,
		sizeXZ = 29,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_75",
		centerX = 732,
		centerZ = 246,
		sizeXZ = 29,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_76",
		centerX = 331,
		centerZ = 719,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_77",
		centerX = 350,
		centerZ = 719,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_78",
		centerX = 424,
		centerZ = 396,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_79",
		centerX = 318,
		centerZ = 485,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_80",
		centerX = 308,
		centerZ = 500,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_81",
		centerX = 350,
		centerZ = 320,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_82",
		centerX = 331,
		centerZ = 314,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_83",
		centerX = 312,
		centerZ = 321,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_84",
		centerX = 293,
		centerZ = 320,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_85",
		centerX = 283,
		centerZ = 307,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_86",
		centerX = 229,
		centerZ = 210,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_87",
		centerX = 562,
		centerZ = 50,
		sizeXZ = 28,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_88",
		centerX = 353,
		centerZ = 503,
		sizeXZ = 24,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_89",
		centerX = 743,
		centerZ = 238,
		sizeXZ = 24,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_90",
		centerX = 429,
		centerZ = 98,
		sizeXZ = 24,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_91",
		centerX = 416,
		centerZ = 103,
		sizeXZ = 24,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_92",
		centerX = 757,
		centerZ = 288,
		sizeXZ = 24,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_93",
		centerX = 298,
		centerZ = 336,
		sizeXZ = 23,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_94",
		centerX = 292,
		centerZ = 352,
		sizeXZ = 23,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_95",
		centerX = 282,
		centerZ = 362,
		sizeXZ = 23,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_96",
		centerX = 360,
		centerZ = 490,
		sizeXZ = 23,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_97",
		centerX = 212,
		centerZ = 222,
		sizeXZ = 22,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_98",
		centerX = 253,
		centerZ = 179,
		sizeXZ = 22,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_99",
		centerX = 253,
		centerZ = 161,
		sizeXZ = 22,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_100",
		centerX = 278,
		centerZ = 188,
		sizeXZ = 22,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_101",
		centerX = 528.3,
		centerZ = 207.6,
		sizeXZ = 50,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_102",
		centerX = 694.2,
		centerZ = 317.9,
		sizeXZ = 50,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
	{
		name = "Kyusyu_103",
		centerX = 530.9,
		centerZ = 232.4,
		sizeXZ = 50,
		baseY = 25,
		thickness = 20,
		grid = 2,
		hillAmplitude = 1,
		hillScale = 100,
		seed = 0,
		generateOcean = false,
		baseMaterial = Enum.Material.LeafyGrass,
	},
}
